### PR TITLE
Fixed some typos in README.md

### PR DESCRIPTION
**Pull request by achoosv**

### CODE REVIEW

**Comment by jerdog** [comment]
This pull request has been mentioned on **Auth0 Community**. There might be relevant details there:

https://community.auth0.com/t/celebrate-hacktoberfest-2018-with-auth0/16159/16

**Comment by jerdog** [comment]
Please adjust merge conflicts and resubmit

**Comment by achoosv** [comment]
@jerdog Resolved merge conflicts.

**Comment by beardaway** [comment]
Hey there @achoosv ! Thanks a lot for the contribution but we already merge the same changes suggested by another developer. However I highly encourage you to stay in our PR land and find another valuable contribution to make! 🤓

**Pull request closed without merging**
